using System.Text;
using MemShack.Application.Entities;
using MemShack.Core.Constants;
using MemShack.Core.Utilities;

namespace MemShack.Application.Onboarding;

public sealed class OnboardingBootstrapService
{
    public EntityRegistry QuickSetup(OnboardingSetup setup, string? configDirectory = null)
    {
        var registry = EntityRegistry.Load(configDirectory);
        registry.Seed(setup.Mode, setup.People, setup.Projects, setup.Aliases);
        GenerateBootstrapFiles(setup, configDirectory);
        return registry;
    }

    public void GenerateBootstrapFiles(OnboardingSetup setup, string? configDirectory = null)
    {
        var outputDirectory = ResolveConfigDirectory(configDirectory);
        Directory.CreateDirectory(outputDirectory);

        var entityCodes = BuildEntityCodes(setup.People, setup.Projects);
        File.WriteAllText(Path.Combine(outputDirectory, ConfigFileNames.AaakEntitiesMarkdown), RenderAaakRegistry(setup, entityCodes));
        File.WriteAllText(Path.Combine(outputDirectory, ConfigFileNames.CriticalFactsMarkdown), RenderCriticalFacts(setup, entityCodes));
    }

    private static string ResolveConfigDirectory(string? configDirectory)
    {
        if (!string.IsNullOrWhiteSpace(configDirectory))
        {
            return Path.GetFullPath(PathUtilities.ExpandHome(configDirectory));
        }

        return MempalaceDefaults.GetDefaultConfigDirectory(PathUtilities.GetHomeDirectory());
    }

    private static IReadOnlyDictionary<string, string> BuildEntityCodes(
        IReadOnlyList<OnboardingPerson> people,
        IReadOnlyList<string> projects)
    {
        var codes = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var name in people.Select(person => person.Name).Concat(projects))
        {
            if (string.IsNullOrWhiteSpace(name))
            {
                continue;
            }

            var baseCodeLength = Math.Min(name.Length, 3);
            var code = name[..baseCodeLength].ToUpperInvariant();
            var index = Math.Min(name.Length, 4);
            while (codes.Values.Contains(code, StringComparer.Ordinal))
            {
                code = name[..Math.Min(name.Length, index)].ToUpperInvariant();
                index = Math.Min(name.Length, index + 1);
                if (index == name.Length && codes.Values.Contains(code, StringComparer.Ordinal))
                {
                    code = $"{code}{codes.Count + 1}";
                    break;
                }
            }

            codes[name] = code;
        }

        return codes;
    }

    private static string RenderAaakRegistry(OnboardingSetup setup, IReadOnlyDictionary<string, string> entityCodes)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# AAAK Entity Registry");
        builder.AppendLine("# Auto-generated by MemShack onboarding bootstrap.");
        builder.AppendLine();
        builder.AppendLine("## People");
        foreach (var person in setup.People)
        {
            if (entityCodes.TryGetValue(person.Name, out var code))
            {
                builder.AppendLine(string.IsNullOrWhiteSpace(person.Relationship)
                    ? $"  {code}={person.Name}"
                    : $"  {code}={person.Name} ({person.Relationship})");
            }
        }

        if (setup.Projects.Count > 0)
        {
            builder.AppendLine();
            builder.AppendLine("## Projects");
            foreach (var project in setup.Projects)
            {
                if (entityCodes.TryGetValue(project, out var code))
                {
                    builder.AppendLine($"  {code}={project}");
                }
            }
        }

        builder.AppendLine();
        builder.AppendLine("## AAAK Quick Reference");
        builder.AppendLine("  Symbols: *=emotion marker | !=warning | ->=relationship |=separator");
        builder.AppendLine("  Structure: KEY:value | GROUP(details) | entity.attribute");
        builder.AppendLine("  Read naturally - expand codes, treat markers as emotional context.");
        return builder.ToString();
    }

    private static string RenderCriticalFacts(OnboardingSetup setup, IReadOnlyDictionary<string, string> entityCodes)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# Critical Facts (bootstrap - will be enriched after mining)");
        builder.AppendLine();

        var personal = setup.People.Where(person => string.Equals(person.Context, "personal", StringComparison.Ordinal)).ToArray();
        var work = setup.People.Where(person => string.Equals(person.Context, "work", StringComparison.Ordinal)).ToArray();

        if (personal.Length > 0)
        {
            builder.AppendLine("## People (personal)");
            foreach (var person in personal)
            {
                builder.AppendLine(RenderFactLine(person, entityCodes));
            }

            builder.AppendLine();
        }

        if (work.Length > 0)
        {
            builder.AppendLine("## People (work)");
            foreach (var person in work)
            {
                builder.AppendLine(RenderFactLine(person, entityCodes));
            }

            builder.AppendLine();
        }

        if (setup.Projects.Count > 0)
        {
            builder.AppendLine("## Projects");
            foreach (var project in setup.Projects)
            {
                builder.AppendLine($"- **{project}**");
            }

            builder.AppendLine();
        }

        builder.AppendLine("## Palace");
        builder.AppendLine($"Wings: {string.Join(", ", setup.Wings)}");
        builder.AppendLine($"Mode: {setup.Mode}");
        builder.AppendLine();
        builder.AppendLine("*This file will be enriched by later mining and fact extraction.*");
        return builder.ToString();
    }

    private static string RenderFactLine(OnboardingPerson person, IReadOnlyDictionary<string, string> entityCodes)
    {
        var code = entityCodes.TryGetValue(person.Name, out var resolvedCode) ? resolvedCode : person.Name[..Math.Min(3, person.Name.Length)].ToUpperInvariant();
        return string.IsNullOrWhiteSpace(person.Relationship)
            ? $"- **{person.Name}** ({code})"
            : $"- **{person.Name}** ({code}) - {person.Relationship}";
    }
}
